auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: pretty

title: linjunzhe.github.com
url: http://linjunzhe.github.com
feed: /atom.xml
author_info: <a href="http://linjunzhe.github.com/">StarWalker</a>
